/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import ShirtSpace from "../assets/3D/shirt_baked_2.glb";

const context = createContext();

const Shirt = ({ children, ...props }) => {
  const { nodes } = useGLTF(ShirtSpace);
  const instances = useMemo(
    () => ({
      TShirtmale: nodes.T_Shirt_male,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <instances.TShirtmale
          name="T_Shirt_male"
          position={[0.419, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: "T_Shirt_male" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload(ShirtSpace);
